name = "atria-tg-bot"
main = "src/index.js"
compatibility_date = "2025-01-01"

# ---------- KV برای dedup سبک ----------
[[kv_namespaces]]
binding = "DEDUP_KV"
id = "394aa4e0f3fb41b387269e9b4d4eefaa"

# ---------- D1 برای ذخیره‌ی پیام‌ها و تحلیل‌ها ----------
[[d1_databases]]
binding = "DB"
database_name = "atria-tg-bot"
database_id = "9e075ad6-7ca1-4d01-ab20-b93a09aa3c17"

# ---------- Durable Object ----------
[[durable_objects.bindings]]
name = "CHAT_SESSION"
class_name = "ChatSession"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatSession"]

# secret ها با `wrangler secret put` ست می‌شن:
# BOT_TOKEN, BOT_USERNAME, BOT_ID, ATRIA_API_KEY, WEBHOOK_SECRET